/**
 * Column helpers shared by every schema file. Column names come from the
 * TypeScript keys (camelCase), so raw SQL quotes them: "windowCloseMin".
 * See docs/data-model.md, "Conventions".
 */
import {
  date,
  doublePrecision,
  integer,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core';
import { uuidv7 } from 'uuidv7';

/** UUIDv7 primary key, generated by the app so ids sort by creation time. */
export const pk = () =>
  uuid()
    .primaryKey()
    .$defaultFn(() => uuidv7());

/** An instant: timestamptz, stored in UTC, shown in Asia/Colombo. */
export const instant = () => timestamp({ withTimezone: true, mode: 'date' });
export const createdAt = () => instant().notNull().defaultNow();
export const updatedAt = () =>
  instant()
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

/** A business date: 'YYYY-MM-DD', always the Asia/Colombo date. */
export const businessDate = () => date({ mode: 'string' });

/** A clock time as minutes after midnight: 05:30 is 330. */
export const minutes = () => integer();

/** kg, m³, km, litres and durations in minutes; compared with a 1e-6 tolerance. */
export const measure = () => doublePrecision();

/** Optimistic concurrency: drives ETag and If-Match. */
export const version = () => integer().notNull().default(1);
