import {
  effects,
  font,
  leading,
  palette,
  radius,
  semantic,
  shadow,
  size,
  space,
  status,
  textStyles,
  type TextStyle,
} from './tokens.ts';

/**
 * Renders the token object into two stylesheets:
 * - tokens.css: plain CSS custom properties and `.type-*` text-style classes. Colours use the
 *   shadcn names (--primary, --border, ...). Everything that would clash with a Tailwind theme
 *   namespace (--radius-*, --shadow-*, --font-*) carries a --compass- prefix.
 * - tailwind.css: the Tailwind 4 theme, built only from those custom properties.
 */

const HEADER =
  '/* Generated by `pnpm --filter @compass/ui-tokens build` from src/tokens.ts. Do not edit. */';

type Entry = readonly [name: string, value: string];

export const kebab = (key: string): string =>
  key.replace(/\./g, '-').replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

/** Palette entries as [css name, value]: base colours by name, scales as <scale>-<step>. */
export const paletteEntries = (): Entry[] => {
  const entries: Entry[] = [];
  for (const [scale, steps] of Object.entries(palette)) {
    for (const [step, value] of Object.entries(steps)) {
      entries.push([scale === 'base' ? step : `${scale}-${step}`, value]);
    }
  }
  return entries;
};

const paletteVarFor = (() => {
  const byValue = new Map<string, string>();
  for (const [name, value] of paletteEntries()) {
    if (!byValue.has(value)) byValue.set(value, name);
  }
  return (value: string): string => {
    const name = byValue.get(value);
    return name ? `var(--${name})` : value;
  };
})();

export const semanticEntries = (): Entry[] =>
  Object.entries(semantic).map(([key, value]) => [kebab(key), value]);

export const statusEntries = (): Entry[] => {
  const entries: Entry[] = [];
  for (const [tone, parts] of Object.entries(status)) {
    for (const [part, value] of Object.entries(parts)) {
      entries.push([`status-${kebab(tone)}-${part}`, value]);
    }
  }
  return entries;
};

const px = (n: number): string => (n === 0 ? '0' : `${n}px`);

const textStyleRule = (name: string, style: TextStyle): string => {
  const lines = [
    `  font-family: var(--compass-font-${style.family});`,
    `  font-size: ${px(style.size)};`,
    `  font-weight: ${style.weight};`,
    `  line-height: ${style.lineHeight === 'auto' ? 'var(--compass-leading-auto)' : px(style.lineHeight)};`,
    `  letter-spacing: ${px(style.letterSpacing)};`,
  ];
  const source = style.figma ? style.figma : 'raw value in frames, no Figma style';
  return `  /* ${source} */\n  .type-${name} {\n  ${lines.join('\n  ')}\n  }`;
};

const block = (selector: string, entries: Entry[], indent = '  '): string =>
  `${selector} {\n${entries.map(([n, v]) => `${indent}--${n}: ${v};`).join('\n')}\n}`;

export const renderTokensCss = (): string => {
  const root: Entry[] = [
    ...paletteEntries(),
    ...semanticEntries().map(([n, v]): Entry => [n, paletteVarFor(v)]),
    ...Object.entries(effects).map(([k, v]): Entry => [kebab(k), v]),
    ...statusEntries().map(([n, v]): Entry => [n, paletteVarFor(v)]),
    ['radius', radius.md],
    ...Object.entries(radius).map(([k, v]): Entry => [`compass-radius-${k}`, v]),
    ...Object.entries(space).map(([k, v]): Entry => [`compass-space-${kebab(k)}`, v]),
    ...Object.entries(size).map(([k, v]): Entry => [`compass-size-${kebab(k)}`, v]),
    ...Object.entries(shadow).map(([k, v]): Entry => [`compass-shadow-${k}`, v]),
    ...Object.entries(leading).map(([k, v]): Entry => [`compass-leading-${k}`, v]),
    ...Object.entries(font).map(([k, v]): Entry => [`compass-font-${k}`, v]),
  ];

  const touch: Entry[] = [
    ['compass-size-control', size.touchTarget],
    ['compass-size-control-sm', size.touchTarget],
  ];

  const classes = Object.entries(textStyles)
    .map(([name, style]) => textStyleRule(name, style))
    .join('\n\n');

  return [
    HEADER,
    '',
    block(':root', root),
    '',
    '/* Dock and driver shells: 44 px minimum targets. */',
    block('[data-density="touch"]', touch),
    '',
    '/* Compass text styles. Colour comes from a text-* utility, never from the style. */',
    `@layer components {\n${classes}\n}`,
    '',
  ].join('\n');
};

export const renderTailwindCss = (): string => {
  const colors: Entry[] = [
    ...paletteEntries().map(([n]): Entry => [`color-${n}`, `var(--${n})`]),
    ...semanticEntries().map(([n]): Entry => [`color-${n}`, `var(--${n})`]),
    ...Object.keys(effects).map((k): Entry => [`color-${kebab(k)}`, `var(--${kebab(k)})`]),
    ...statusEntries().map(([n]): Entry => [`color-${n}`, `var(--${n})`]),
  ];
  const rest: Entry[] = [
    ...Object.keys(radius).map((k): Entry => [`radius-${k}`, `var(--compass-radius-${k})`]),
    ...Object.keys(shadow).map((k): Entry => [`shadow-${k}`, `var(--compass-shadow-${k})`]),
    ...Object.keys(font).map((k): Entry => [`font-${k}`, `var(--compass-font-${k})`]),
    ...Object.keys(leading).map((k): Entry => [`leading-${k}`, `var(--compass-leading-${k})`]),
  ];

  return [
    HEADER,
    '/* Import after tailwindcss and tokens.css. Tailwind gets the Compass tokens and nothing else:',
    '   its default colours, fonts, radii, shadows and font sizes are removed, so use the .type-*',
    '   text styles for type. Spacing keeps Tailwind\'s 4 px scale, which matches space/* in Figma. */',
    '',
    '@theme {',
    '  --color-*: initial;',
    '  --font-*: initial;',
    '  --radius-*: initial;',
    '  --shadow-*: initial;',
    '  --text-*: initial;',
    '}',
    '',
    block('@theme inline', [...colors, ...rest]),
    '',
  ].join('\n');
};
